// Mocks generated by Mockito 5.4.6 from annotations
// in bli/test/features/preferences/bloc/preferences_bloc_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:bli/features/preferences/models/user_preferences.dart' as _i2;
import 'package:bli/features/preferences/services/preferences_service.dart'
    as _i3;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeUserPreferences_0 extends _i1.SmartFake
    implements _i2.UserPreferences {
  _FakeUserPreferences_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [PreferencesService].
///
/// See the documentation for Mockito's code generation for more information.
class MockPreferencesService extends _i1.Mock
    implements _i3.PreferencesService {
  @override
  _i4.Future<_i2.UserPreferences> getLocalPreferences() =>
      (super.noSuchMethod(
            Invocation.method(#getLocalPreferences, []),
            returnValue: _i4.Future<_i2.UserPreferences>.value(
              _FakeUserPreferences_0(
                this,
                Invocation.method(#getLocalPreferences, []),
              ),
            ),
            returnValueForMissingStub: _i4.Future<_i2.UserPreferences>.value(
              _FakeUserPreferences_0(
                this,
                Invocation.method(#getLocalPreferences, []),
              ),
            ),
          )
          as _i4.Future<_i2.UserPreferences>);

  @override
  _i4.Future<void> saveLocalPreferences(_i2.UserPreferences? preferences) =>
      (super.noSuchMethod(
            Invocation.method(#saveLocalPreferences, [preferences]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> clearLocalPreferences() =>
      (super.noSuchMethod(
            Invocation.method(#clearLocalPreferences, []),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<_i2.UserPreferences?> getCloudPreferences(String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#getCloudPreferences, [userId]),
            returnValue: _i4.Future<_i2.UserPreferences?>.value(),
            returnValueForMissingStub: _i4.Future<_i2.UserPreferences?>.value(),
          )
          as _i4.Future<_i2.UserPreferences?>);

  @override
  _i4.Future<void> saveCloudPreferences(
    String? userId,
    _i2.UserPreferences? preferences,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#saveCloudPreferences, [userId, preferences]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> deleteCloudPreferences(String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#deleteCloudPreferences, [userId]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Stream<_i2.UserPreferences?> watchCloudPreferences(String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#watchCloudPreferences, [userId]),
            returnValue: _i4.Stream<_i2.UserPreferences?>.empty(),
            returnValueForMissingStub: _i4.Stream<_i2.UserPreferences?>.empty(),
          )
          as _i4.Stream<_i2.UserPreferences?>);
}
