// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDEbmvlq-P93-icvTFC9va-H22keCDKBmQ',
    appId: '1:402145256946:web:f36996e1d7a2abc9f0b76b',
    messagingSenderId: '402145256946',
    projectId: 'bremen-livability-index',
    authDomain: 'bremen-livability-index.firebaseapp.com',
    storageBucket: 'bremen-livability-index.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC1KBuReBqA4wa5ReVcknBmUkBbk3RscbQ',
    appId: '1:402145256946:android:108cf6fda1eda670f0b76b',
    messagingSenderId: '402145256946',
    projectId: 'bremen-livability-index',
    storageBucket: 'bremen-livability-index.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCsNUA4Wh5ZUFJQkPFaRqGKqLQjY2D9gXM',
    appId: '1:402145256946:ios:6e26df3ff0e0d7cef0b76b',
    messagingSenderId: '402145256946',
    projectId: 'bremen-livability-index',
    storageBucket: 'bremen-livability-index.firebasestorage.app',
    iosClientId:
        '402145256946-eeopjp0jqhujcvseq2rts2fcbjr8t3pt.apps.googleusercontent.com',
    iosBundleId: 'com.example.bli',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCsNUA4Wh5ZUFJQkPFaRqGKqLQjY2D9gXM',
    appId: '1:402145256946:ios:6e26df3ff0e0d7cef0b76b',
    messagingSenderId: '402145256946',
    projectId: 'bremen-livability-index',
    storageBucket: 'bremen-livability-index.firebasestorage.app',
    iosClientId:
        '402145256946-eeopjp0jqhujcvseq2rts2fcbjr8t3pt.apps.googleusercontent.com',
    iosBundleId: 'com.example.bli',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDEbmvlq-P93-icvTFC9va-H22keCDKBmQ',
    appId: '1:402145256946:web:520d0eb1552ad56ff0b76b',
    messagingSenderId: '402145256946',
    projectId: 'bremen-livability-index',
    authDomain: 'bremen-livability-index.firebaseapp.com',
    storageBucket: 'bremen-livability-index.firebasestorage.app',
  );
}
