// Mocks generated by Mockito 5.4.6 from annotations
// in bli/test/features/onboarding/widgets/onboarding_widgets_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:bli/features/auth/models/user.dart' as _i5;
import 'package:bli/features/auth/services/auth_service.dart' as _i2;
import 'package:firebase_auth/firebase_auth.dart' as _i4;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [AuthService].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthService extends _i1.Mock implements _i2.AuthService {
  @override
  _i3.Stream<_i4.User?> get authStateChanges =>
      (super.noSuchMethod(
            Invocation.getter(#authStateChanges),
            returnValue: _i3.Stream<_i4.User?>.empty(),
            returnValueForMissingStub: _i3.Stream<_i4.User?>.empty(),
          )
          as _i3.Stream<_i4.User?>);

  @override
  _i3.Future<_i5.AppUser?> signInWithGoogle() =>
      (super.noSuchMethod(
            Invocation.method(#signInWithGoogle, []),
            returnValue: _i3.Future<_i5.AppUser?>.value(),
            returnValueForMissingStub: _i3.Future<_i5.AppUser?>.value(),
          )
          as _i3.Future<_i5.AppUser?>);

  @override
  _i3.Future<_i5.AppUser?> signInWithGitHub() =>
      (super.noSuchMethod(
            Invocation.method(#signInWithGitHub, []),
            returnValue: _i3.Future<_i5.AppUser?>.value(),
            returnValueForMissingStub: _i3.Future<_i5.AppUser?>.value(),
          )
          as _i3.Future<_i5.AppUser?>);

  @override
  _i3.Future<void> sendEmailLink(String? email) =>
      (super.noSuchMethod(
            Invocation.method(#sendEmailLink, [email]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<_i5.AppUser?> signInWithEmailLink(String? email, String? link) =>
      (super.noSuchMethod(
            Invocation.method(#signInWithEmailLink, [email, link]),
            returnValue: _i3.Future<_i5.AppUser?>.value(),
            returnValueForMissingStub: _i3.Future<_i5.AppUser?>.value(),
          )
          as _i3.Future<_i5.AppUser?>);

  @override
  _i3.Future<void> sendPhoneVerification(
    String? phoneNumber, {
    required dynamic Function(String)? onCodeSent,
    required dynamic Function(String)? onError,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #sendPhoneVerification,
              [phoneNumber],
              {#onCodeSent: onCodeSent, #onError: onError},
            ),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<_i5.AppUser?> verifyPhoneCode(
    String? verificationId,
    String? smsCode,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#verifyPhoneCode, [verificationId, smsCode]),
            returnValue: _i3.Future<_i5.AppUser?>.value(),
            returnValueForMissingStub: _i3.Future<_i5.AppUser?>.value(),
          )
          as _i3.Future<_i5.AppUser?>);

  @override
  _i3.Future<_i5.AppUser?> signInAsGuest() =>
      (super.noSuchMethod(
            Invocation.method(#signInAsGuest, []),
            returnValue: _i3.Future<_i5.AppUser?>.value(),
            returnValueForMissingStub: _i3.Future<_i5.AppUser?>.value(),
          )
          as _i3.Future<_i5.AppUser?>);

  @override
  _i3.Future<void> signOut() =>
      (super.noSuchMethod(
            Invocation.method(#signOut, []),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<_i5.AppUser?> getCurrentUser() =>
      (super.noSuchMethod(
            Invocation.method(#getCurrentUser, []),
            returnValue: _i3.Future<_i5.AppUser?>.value(),
            returnValueForMissingStub: _i3.Future<_i5.AppUser?>.value(),
          )
          as _i3.Future<_i5.AppUser?>);

  @override
  _i3.Future<void> savePendingEmail(String? email) =>
      (super.noSuchMethod(
            Invocation.method(#savePendingEmail, [email]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<String?> getPendingEmail() =>
      (super.noSuchMethod(
            Invocation.method(#getPendingEmail, []),
            returnValue: _i3.Future<String?>.value(),
            returnValueForMissingStub: _i3.Future<String?>.value(),
          )
          as _i3.Future<String?>);

  @override
  _i3.Future<void> clearPendingEmail() =>
      (super.noSuchMethod(
            Invocation.method(#clearPendingEmail, []),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);
}
